version: '3'
services:
  gpt-meeting-service:
    container_name: service
    image: pipiya/gpt-meeting-service:v1.2.2
    ports:
      - 8000:8000
    volumes:
      - ./conf:/data/conf
    depends_on:
      - mongodb
    networks:
      - meeting-network

  gpt-meeting-web:
    container_name: web
    image: pipiya/gpt-meeting-web:v1.1
    ports:
      - 8080:8080
    depends_on:
      - gpt-meeting-service
    networks:
      - meeting-network

  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwd
    networks:
      - meeting-network

networks:
  meeting-network:
